"use client";

// EditAuditModal — admin only. Edits one audit's page_type, page_url and
// doctrine_version via PATCH /api/audits/[id]. Insert/score fields are
// generated by the scoring pipeline and not user-editable.
//
// SP-7 / V26.AG.

import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Button, FormRow, Modal } from "@growthcro/ui";
import type { Audit } from "@growthcro/data";

type Props = {
  audit: Audit;
  open: boolean;
  onClose: () => void;
};

const PAGE_TYPES = [
  "home",
  "pdp",
  "collection",
  "checkout",
  "article",
  "quiz",
  "lp_lead_gen",
  "lp_advertorial",
  "lp_sales",
  "lp_listicle",
  "lp_squeeze",
  "lp_other",
];

const DOCTRINE_VERSIONS = ["v3.2.1", "v3.3"];

export function EditAuditModal({ audit, open, onClose }: Props) {
  const router = useRouter();
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function onSubmit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    if (submitting) return;
    setSubmitting(true);
    setError(null);

    const fd = new FormData(e.currentTarget);
    const payload = {
      page_type: String(fd.get("page_type") ?? ""),
      page_url: String(fd.get("page_url") ?? "").trim() || null,
      doctrine_version: String(fd.get("doctrine_version") ?? "v3.2.1"),
    };

    try {
      const res = await fetch(`/api/audits/${audit.id}`, {
        method: "PATCH",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(payload),
      });
      const json = (await res.json()) as { ok: boolean; error?: string };
      if (!res.ok || !json.ok) {
        setError(json.error ?? `HTTP ${res.status}`);
        setSubmitting(false);
        return;
      }
      onClose();
      router.refresh();
    } catch (err) {
      setError((err as Error).message);
      setSubmitting(false);
    }
  }

  return (
    <Modal open={open} onClose={onClose} title="Editer l'audit" width="540px">
      <form onSubmit={onSubmit} className="gc-stack" style={{ gap: 12 }}>
        <FormRow label="Type de page" htmlFor="audit-edit-page-type">
          <select
            id="audit-edit-page-type"
            name="page_type"
            className="gc-form-row__select"
            defaultValue={audit.page_type}
          >
            {PAGE_TYPES.map((t) => (
              <option key={t} value={t}>
                {t}
              </option>
            ))}
          </select>
        </FormRow>

        <FormRow label="URL de la page" htmlFor="audit-edit-page-url">
          <input
            id="audit-edit-page-url"
            name="page_url"
            className="gc-form-row__input"
            type="url"
            defaultValue={audit.page_url ?? ""}
            placeholder="https://example.com/produit"
          />
        </FormRow>

        <FormRow label="Version doctrine" htmlFor="audit-edit-doctrine">
          <select
            id="audit-edit-doctrine"
            name="doctrine_version"
            className="gc-form-row__select"
            defaultValue={audit.doctrine_version}
          >
            {DOCTRINE_VERSIONS.map((v) => (
              <option key={v} value={v}>
                {v}
              </option>
            ))}
          </select>
        </FormRow>

        {error ? (
          <p role="alert" className="gc-form-row__error">
            {error}
          </p>
        ) : null}

        <div style={{ display: "flex", justifyContent: "flex-end", gap: 8 }}>
          <Button type="button" variant="ghost" onClick={onClose} disabled={submitting}>
            Annuler
          </Button>
          <Button type="submit" variant="primary" disabled={submitting}>
            {submitting ? "Enregistrement…" : "Enregistrer"}
          </Button>
        </div>
      </form>
    </Modal>
  );
}
